services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drupal-initia
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DRUPAL_DATABASE_HOST: db
      DRUPAL_DATABASE_USER: drupal
      DRUPAL_DATABASE_PASSWORD: drupal
      DRUPAL_DATABASE_NAME: drupal
    volumes:
      - ./drupal:/var/www/html
    command: >
      sh -c "composer install &&
             apache2-foreground"

  db:
    image: mariadb:latest
    container_name: drupal-initia-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: drupal-initia-phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 64M
      MYSQL_ROOT_PASSWORD: root

volumes:
  drupal-data:
  db-data:
